# Generated by Django 4.2 on 2024-05-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Borrow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('items', models.ManyToManyField(related_name='rooms', to='Borrow.item')),
            ],
        ),
    ]
