# Generated by Django 4.2 on 2024-05-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('holderId', models.IntegerField(default=0)),
                ('roomId', models.IntegerField(default=302)),
            ],
        ),
    ]
