# Generated by Django 4.2 on 2024-06-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Borrow', '0002_alter_item_roomid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='roomId',
            field=models.IntegerField(default=302),
        ),
    ]
